name = "TNRKit"
uuid = "7dfc3ef0-df9b-475f-b8e2-b91f34f5d84d"
authors = ["VictorVanthilt <victor.vanthilt@gmail.com>"]
version = "0.1.0"

[deps]
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
PEPSKit = "52969e89-939e-4361-9b68-9bc7cde4bdeb"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"

[compat]
KrylovKit = "0.9.5"
PEPSKit = "0.5.0"
TensorKit = "0.14"

[extras]
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "QuadGK"]
