name = "TNRKit"
uuid = "7dfc3ef0-df9b-475f-b8e2-b91f34f5d84d"
authors = ["VictorVanthilt <victor.vanthilt@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
OptimKit = "77e91f04-9b3b-57a6-a776-40b61faaebe0"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
OptimKit = "0.3.1"
TensorKit = "0.14"
Zygote = "0.7.3"

[extras]
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "QuadGK"]
